### ISSUE TITLE
Remove close() method?

### ISSUE THREAD

**Issue by ricea** [ricea/websocketstream-explainer#12]
`close()` serves four purposes:
1. Abort the handshake. However, the `signal` passed in the constructor options can also do this.
2. Pass `code` and `reason` to a Close frame after the handshake has completed. However, the `readable.cancel()` and `writable.abort()` methods can also do this.
3. Close even if both `readable` and `writable` are locked. This might be useful if they have been transferred.
4. End the connection unconditionally regardless of the current state.

The last two are the only things that can't be done another way. Are they sufficient to justify the existence of the method?

**Comment by israelidanny** [comment]
IMHO (3) and (4) more than justify this. I am now trying to resolve an issue with Deno where without a proper `close()` it would be very hard to fix the expected DX:
https://github.com/denoland/deno/issues/15616

It's very likely and possible that we've let someone lock the readable() and / or writeable() yet we want to `close()` early and abort everything from a different thread / scope.

**Comment by ricea** [comment]
I've concluded that (3) and (4) are very useful, and `close()` is also nice from an ease-of-use perspective, so I'm not going to remove `close()`.
