### ISSUE TITLE
Cool, but why not as a Built-in native module?

### ISSUE THREAD

**Issue by jimmywarting** [ricea/websocketstream-explainer#4]
Just discovered this new WebSocketStream thing, but why wasn't it considered as a builtin module?

like the key/value storage?
https://developers.google.com/web/updates/2019/03/kv-storage

think that should be the new way of implementing new features...?

Maybe not too late to change it?

**Comment by ricea** [comment]
The primary reason is that it exposes a new capability that is not currently available, ie. backpressure. Modules like kv-storage are built on top of existing platform capabilities.

**Comment by ricea** [comment]
I've asked around, and built-in modules are at a very early stage of standardisation which means we're not ready to build features on them yet.

**Comment by jimmywarting** [comment]
okey
