### ISSUE TITLE
stream close:  reason and codes

### ISSUE THREAD

**Issue by MeirionHughes** [ricea/websocketstream-explainer#6]
quick question for some specifics: so the `connection` resolves to `{readable, writable}`

`ReadableStream` has a `close(reason?)` and, 
`WritableStream` has an `abort(reason?), and its Writer also has `close` and `abort`

do these effect the websocket? if so, 
when `close()`, with/without reason, what websocket code is sent?
when `abort()`, with/without reason, what websocket code is sent?
when `writer.abort()`, with/without reason, what websocket code is sent?

cheers

**Comment by ricea** [comment]
These do affect the WebSocket. I should clarify this in the explainer.

`close()` closes with an "unspecified" code, ie. the Close frame has no body.
`abort()` closed with an unspecified code by default, but you can use `abort({code, reason})` to send a specific code and reason. For example, `abort({code: 4000, reason: 'my reason'})` will close with status code 4000 and reason `my reason`. I'm not 100% confident that this is the right behaviour, but it is what Chromium implements.
`writer.close()` and `writer.abort()` behave the same as the same methods on the WritableStream.
`cancel()` on the ReadableStream behaves like `abort()`, as does `reader.cancel()`.
